### ISSUE TITLE
Blosc:zstd not in list on import

### ISSUE THREAD

**Issue by sbuschjaeger** [fact-project/pyfact#133]
Hi,

I just installed / upgraded pyfact (via pip) and get the following error on import

> Traceback (most recent call last):
>   File "./init.py", line 16, in <module>
>     import fact.io
>   File "/home/buschjae/.local/lib/python3.5/site-packages/fact/io.py", line 52, in <module>
>     zstd_opts = create_blosc_compression_options()
>   File "/home/buschjae/.local/lib/python3.5/site-packages/fact/io.py", line 40, in create_blosc_compression_options
>     complib = ['blosc:' + c for c in compressors].index(complib)
> ValueError: 'blosc:zstd' is not in list

I installed the hdf5plugin (python3 -m pip install --user --upgrade hdf5plugin) and I upgraded h5py (python3 -m pip install --user --upgrade h5py) without any effect.

Best
Sebastian

**Comment by maxnoe** [comment]
For blosc with zstd to work, you need to have `h5py` and `tables` installed and linked vs the same libhdf5. 

I thoguht I catched all the cases where this was not the case.

**Comment by maxnoe** [comment]
Can you give me the output of `pip freeze`?

**Comment by maxnoe** [comment]
When I do a fresh install using pip and using wheels for tables und h5py, I get this:

```
/home/maxnoe/test_h5py/lib/python3.6/site-packages/fact/io.py:61: UserWarning: BLOSC compression for hdf5 not available,
 you will not be able to create or read blosc compressed datasets 
make sure tables and h5py are linked against the same hdf5 library e.g. by installing hdf5 in your system and doing  `pip install --no-binary=tables --no-binary=h5py tables h5py`
  'BLOSC compression for hdf5 not available, you will not be able'
```

using h5py and tables from conda also just works out of the box as they are linked vs the same libhdf

**Comment by sbuschjaeger** [comment]
First: A downgrade to v0.24.0 worked without any problems

Second: `tables` was not installed. With some hiccups (due to my system) I was able to install tables with HDF5 support (e.g. requires libhdf5-dev on ubuntu 16.04). Now pyfact only throws the warning you posted, but seems to work as expected.

I think `tables` should be part of to requirements.txt, shouldnt it?

**Comment by maxnoe** [comment]
Tables **is** a requirement. So it should have been installed.

The only way not to have tables would have been uninstalling it after installing pyfact

**Comment by maxnoe** [comment]
> Second: tables was not installed

Actually, this is impossible. If tables wasn't  installed,  you'd get an import error when importing fact.io as it is importing tables immediately

**Comment by sbuschjaeger** [comment]
I did some testing and as it turns out the problem is a follows: I installed `pyfact` and `h5py` as user. However there was also a system installation of `tables` available. Thus `pyfact` found all requirements (`h5py` and `tables`), but they did not use the same HDF5 library which is necessary as you said in your first post.

**Comment by maxnoe** [comment]
Ok, while this is a strange issue, there should have been no error and just the warning that zstd compression is not available.

**Comment by maxnoe** [comment]
Ah, and I guess the system tables version was so old, that zstd was not yet supported. Can you check the version?

**Comment by maxnoe** [comment]
See #134

**Comment by sbuschjaeger** [comment]
> Ah, and I guess the system tables version was so old, that zstd was not yet supported. Can you check the version?

The version is 3.2.2, which seems to be from around September 2015. If I read the PyTables commits correctly the `blosc:zstd` option has been introduced around September 2016. So yes it seems zstd is not supported in this version.

**Comment by maxnoe** [comment]
Ok, I now added tables 3.3 as requirement which added the zstd support in #134.
So in future this should just work or give the verbose warning about what to do.
