### ISSUE TITLE
read password from enviroment variable and persistent RunDB

### ISSUE THREAD

**Issue by dneise** [fact-project/pyfact#28]
Two things very loosely connected, still together in my mind.

I find it annoying I have to type the std FACT password everytime in my machine. Instead I would like to type it once and for all. This could be solved by a config file, but I feel using enviroment variables e.g. named `FACT_PASSWORD` is also quite common and other programs on my own laptop might also read this in case they need the password. 
Also it is nicely self commenting in code, so when I give a script to somebody and this line throws a `KeyError`:

```
    foobar(os.environ['FACT_PASSWORD'])
```

Then the recipient of this loose script might be able to solve the problem by mere guessing.
I think this is pretty nice. 

-----

I sometimes find myself playing around without network access. Having a local copy of our ~100MB RunInfo table would come in handy then, in case I wanted to know how much data of this or that type we got. At the moment we provide a convenient way of getting access to our DB via `create_factdb_engine`. However quite often people access only the "RunInfo" table, so having a copy on disk (or in mem) could be even more convenient. Something like `joblib.Memory` could be used to store the entire table in a dataframe on disk, which allows also for nice queries. 

I just don't know a nice way for this cache to time out and a nice behaviour. I'd like to have something like this:

If the cache is a day old and there is network access, well then a fresh copy from the DB and give me that else give the cache, no matter how old it might be, it is most often fresh enough.

**Comment by dneise** [comment]
https://github.com/mailgun/expiringdict also came to mind, but this does not like to give me outdated content in case I have no network access. So I think there might be no premade solution for this. 

I would now go on and create a function in pyfact maybe like this:
```{python}
from joblib import Memory
memory = Memory(cachedir='~/.pyfact', verbose=0) # ~ doesn't work here I know ... but you get the point.

def get_database_table(name):
    try:
        # should throw something if no network access, 
        # hopefully does not timeout forever.
        return get_database_table_cached.call(name)  # call() does not read the cache, but writes to it.
     except SomeErrorDueToNoAccessToMysqlServer:
        return get_database_table_cached(name)  # uses cache if it exists.


@memory.cache
def get_database_table_cached(name):
    db = create_factdb_engine()  # works since I stored my password in an enviroment var
    table = pd.read_sql_table(name, db)
    return table
```

**Comment by dneise** [comment]
Ah I just see this still tries to refresh the cache on every call, while it should only do so once a day...
So back to the sketch board.

**Comment by maxnoe** [comment]
The environment variable stuff got implemented in #30.

Isn't this two issues in one? There is even an "and" in the title :D

**Comment by dneise** [comment]
> Isn't this two issues in one? There is even an "and" in the title :D

It is ... but I think writing what comes to mind as an issue much much much better than not writing an issue at all.

**Comment by dneise** [comment]
Only existing issues can be modified by people interested in them including the original author.

**Comment by dneise** [comment]
This is done...
