### ISSUE TITLE
Slowdata not maintained anymore?

### ISSUE THREAD

**Issue by maxnoe** [fact-project/pyfact#5]
Does it make sense to keep the slowdate module since the database does not exist anymore?

**Comment by dneise** [comment]
I guess not.
Does git have sth. like tags? Maybe when we come back to a slowdata DB once, we'd like to have a look at this module again.

**Comment by maxnoe** [comment]
yes. You can do something like:

```
git tag <name> <hash>
git push --tags
```

**Comment by dneise** [comment]
so whoever is going to delete this module should assign a tag like "last_version_with_slowdata_db" to that version? I have no idea what a good name for a tag is ... possible this name is a lie very soon :-(
