### ISSUE TITLE
More convinient way to read data.

### ISSUE THREAD

**Issue by kbruegge** [fact-project/pyfact#62]
So right now I have to do the following to work with analysed data.
```
    events = read_h5py(data_path, key='events', columns=columns)
    events = events.rename(columns={'RUNID':'run_id', 'NIGHT':'night'})

    runs = read_h5py(data_path, key='runs')
    runs['run_start'] = pd.to_datetime(runs['run_start'])
    runs['run_stop'] = pd.to_datetime(runs['run_stop'])
```
I have to do this in all scripts where I want to work with actual data. 
Can we find a more conviniet way to do this?

**Comment by maxnoe** [comment]
This got fixed some time ago. Datetime columns should be transformed automatically now.
