### ISSUE TITLE
`run2dt` - wrong function name, and maybe more sugar ? 

### ISSUE THREAD

**Issue by dneise** [fact-project/pyfact#66]
I just stumbled upon the use of `run2dt` in another project and had two issues:

1. I didn't understand *in detail* what the code in that project did and
2. the `run2dt` function name did not remind me "good enough" about what it needs and what it is doing.

---
### 2. function name

Looking at [the definition](https://github.com/fact-project/pyfact/blob/master/fact/time.py#L55) revealed. It does not deal with *runs* but with these "funny night ints". If people see "20170102_103" then they usually parse it like this: "yyyymmdd_rrr" so the last 3 digits are refered to as *run*, not the first 8 digits. We usually call this "nightint" if I remember correctly.

So a better name for this function should be "nightint2dt", but this is also not good, as the function wants a string, not an int, so it may better be named "nightintstring2dt" ... or so ... 

---

### 1. usage of this function in other projects.

In order to use this function, the author in this other project needed to manipulate a file path in order to find out the *nightintstring* and give it to `run2dt`. Manipulating strings and paths is fairly low level, and I think if we provide helper functions in `pyfact` we may think about tools that permit users to push this low level shit away from their code, if possible.

In this example the *nightintstring* was part of the filename and it was followed by and underscore `_`, just like in the example above. I think we could write a function that takes a complete path, takes just the filename and searches with a regex for **exactly 8 digits the first two being "20" followed by an underscore** and returning the aware `datetime` object that is also returned by `run2dt`. 

I think the function should maybe have this interface:
```
def guess_path2dt(path, re=r'.*?(20\d{6})_.*'):
   # ...
   return dt
```

It simply strips of the filename using `os.path.basename` and applies a regex and turns the result into an aware datetime object. Users can modify the regex, but usually it simply matches the first occurrence of "8 digits starting with "20" with a trailing underscore". This should fit many use cases.

What do you think? Does this sound useful enough for you, or is it too specialized to be part of pyfact?

**Comment by maxnoe** [comment]
this was removed in the refactoring of the time module.
