### ISSUE TITLE
fact.path, night is not reduced to integer

### ISSUE THREAD

**Issue by relleums** [fact-project/pyfact#74]
This will fail:
```python
assert '.' not in tree_path(20170901.0, 123, 'prefix', '_suffix')
```
Since the run was explicitly casted into an int I assume the night should also be casted to int. This way ```fact.path.template_to_path``` could deal with float inputs

**Comment by dneise** [comment]
I think `float` should not be supported as valid input to these path functions. 

To much can go wrong, which the user might not have expected:
```ipython
In [8]: assert 20160401 == int(20160401.0)   # ok fine

In [9]: assert 20160401 == int(20160401.0 - 1e-8)  # not fine
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-9-d9c2cf932cec> in <module>()
----> 1 assert 20160401 == int(20160401.0 - 1e-8)
```

**Comment by relleums** [comment]
Restricting ```fact.path.template_to_path``` to ```int``` is fine for me. I understand your fear of unexpected behaviour.

**Comment by dneise** [comment]
Wontfix
