### ISSUE TITLE
store information about broken, crazy, dead, twin, whatever pixel and patches

### ISSUE THREAD

**Issue by dneise** [fact-project/pyfact#9]
We have collection quite some knowledge about broken, dead, twin, crazy, slimy, handy, grumpy, smarty, jokey, smurfy, and what ever else pixels and patches now.

Some of these pixels might have been their feature only for a certain time span.

I would like to have a central place from where to retrieve this information, say a DB. So the different tools we use in FACT can share the same knowledge somehow. 

Neither this DB exists at the moment, nor can we apparently get all our worker nodes to have internet access, so this might stay a dream forever.

For pyfact however, I'd like to have an easy possibility to get this information somehow.

``` python
import fact

print(fact.fishy_pixels_n_patches)  # <-- a DataFrame maybe
```

**Comment by dneise** [comment]
This information, I would then like to have available in `plt.factcamera` so users can easily treat special pixel in a special way, when plotting.

**Comment by maxnoe** [comment]
also implemented in `fact.instrument.camera`
