### ISSUE TITLE
Weird import behaviour

### ISSUE THREAD

**Issue by kbruegge** [fact-project/pyfact#97]
This works:

```
In [1]: import fact.io
In [2]: fact.io.read_data
Out[2]: <function fact.io.read_data>
```
But this does not:

```
In [1]: import fact

In [2]: fact.io.read_data
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-5092b721dcb9> in <module>()
----> 1 fact.io.read_data

AttributeError: module 'fact' has no attribute 'io'
```

I find this non intuitive. Or is this expected behaviour?

**Comment by dneise** [comment]
similar stuff happens in scipy
```
In [1]: import scipy.special
In [2]: scipy.special.factorial(6)
Out[2]: array(720.)
```
But not
```
In [1]: import scipy
In [2]: scipy.special.factorial(6)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-044c8efbc812> in <module>()
----> 1 scipy.special.factorial(6)

AttributeError: module 'scipy' has no attribute 'special'
```

**Comment by dneise** [comment]
I find that also non intuitive, but I guess there are reasons.... dunno.

**Comment by kbruegge** [comment]
Yeah. I've seen that to. It does work in numpy though

```
In [1]: import numpy as np

In [2]: np.linalg.norm
Out[2]: <function numpy.linalg.linalg.norm>

In [3]: np.random.uniform
Out[3]: <function RandomState.uniform>
```

I guess its a question of style

**Comment by dneise** [comment]
> I guess its a question of style

I guess so too, technically both must be possible.

I assume import numpy just directly imports more stuff into main memory, whereas scipy does not. So I guess it is not only style but has some (tiny?) performance implications.

**Comment by maxnoe** [comment]
Subpackages are not automatically imported. This is good, as in large modules it might take considerable time to recursively import everything.
So, to make `fact.io` available through only importing `fact`, one has to add. 

```
from . import io

__all__ = [..., 'io']
```
Into `fact/__init__.py`

**Comment by maxnoe** [comment]
Do we want this? I don't think so, with few exceptions everywhere in the python world, subpackages have to be explicitly imported.

**Comment by dneise** [comment]
> Do we want this? I don't think so, with few exceptions everywhere in the python world, subpackages have to be explicitly imported.

This is exactly what I had no idea of. So default pythonic behaviour is what we have and numpy is "breaking the law". 

Then I'd say .. let's leave it as it is ... 

@MaxNoe do you remember why it is considered normal for subpackages to be explicitly imported? 
Performance? explicit over implicit? Reduction of "noise" in most `__init__` files?

**Comment by maxnoe** [comment]
> @MaxNoe do you remember why it is considered normal for subpackages to be explicitly imported?

Like I said, I think it's mostly performance. Recursively importing modules, executing each `__init__.py`, doing all the imports, can be very expensive.

**Comment by maxnoe** [comment]
> So default pythonic behaviour is what we have and numpy is "breaking the law".

Only in some places (where it maybe is not expensive to do so), some deeper submodules are also not imported by `import numpy`. 

A counter-example from the standard lib is `os.path` which becomes available by `import os`
